name: logger_interceptor
description: "A Flutter library that support for write log based on dio library."
version: 0.0.5
repository: https://github.com/kenshite123/c9_logger_interceptor

environment:
  sdk: ">=3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  intl: ^0.18.0
  path_provider: ^2.0.0
  permission_handler: ^11.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0